### ISSUE TITLE
React SPA?

### ISSUE THREAD

**Issue by luko0610** [Zumpel96/Teuerungsportal#98]
Servus, 
sollte Interesse bestehen, würde ich mich bereit erklären, ein React Frontend zu bauen.
In der angehängten file sieht man ein paar views, die ich schnell mit ant design umgesetzt habe.

[Teuerungsportal.webm](https://github.com/Zumpel96/Teuerungsportal/assets/24602363/af62e3d5-5141-45b0-8293-c6ea7acb28d6)

**Comment by Zumpel96** [comment]
Thanks! I am currently using Blazor WASM for the frontend with MudBlazor as the UI Kit. The reason behind this is, that the performance for larger datasets is better by a significant factor (~x50) compared to JavaScript because of the AOT-Compiliation. Switching the Frontend is currently out of question, except for native app integrations (iOS and Android).
